USE PBin;

/*
DROP TABLE [UserRole];
DROP TABLE [Role];

DROP TABLE [SharedPost];
DROP TABLE [FileUpload];
DROP TABLE [Post];
DROP TABLE [WatchWord];
DROP TABLE [User];
*/

CREATE TABLE [User] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[Email] VARCHAR(128) UNIQUE NOT NULL,
	[Password] VARCHAR(128) NOT NULL,
	[DateCreated] DATETIME,
	[FirstName] VARCHAR(64),
	[LastName] VARCHAR(64),
	[Active] BIT
);

CREATE TABLE [Post] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id),
	[Title] VARCHAR(32),
	[Content] VARCHAR(256),
	[DateCreated] DATETIME,	
	[DateExpires] DATETIME,
	[Public] BIT,
	[Enabled] BIT
);

CREATE TABLE [WatchWord] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id),
	[Word] VARCHAR(64)
);

CREATE TABLE [SharedPost] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[PostId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Post](Id),
	[SharedUserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id)
); 

CREATE TABLE [Role](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[Role] VARCHAR(64)
); 

CREATE TABLE [UserRole] (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[RoleId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Role](Id),
	[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id)
);