//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.SharedPost = new HashSet<SharedPost>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpires { get; set; }
        public Nullable<bool> Public { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SharedPost> SharedPost { get; set; }
    }
}
