//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedPost
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public Nullable<System.Guid> SharedUserId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
